Vamos aprender a usar a biblioteca **Numpy** para trabalhar com vetores e matrizes usando Python.

Roteiro:
1. Criando listas e arrays
2. Operações com vetores
3. Criando matrizes
4. Operações com matrizes
5. Seleção e atribuição de valores
6. Transformações de matrizes

In [1]:
# importar a biblioteca
import numpy as np

# 1. Criando listas e arrays

In [2]:
# criar uma lista simples
my_list = [0,1,2,3,4,5]

# criar um array com numpy
my_array = np.array([0,1,2,3,4,5])

Verificar a diferença entre a lista e o array

In [3]:
print(my_list)
print(my_array)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [4]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


# 2. Operações com vetores

## 2.1 Operador de soma (+) e subtração (-)

In [5]:
# fazer a operação de soma na lista
print(my_list + 1)

TypeError: can only concatenate list (not "int") to list

In [6]:
# fazer a operação de soma no array
print(my_array + 1)

[1 2 3 4 5 6]


In [7]:
# somar duas listas
print(my_list + my_list)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]


In [8]:
# somar dois arrays
print(my_array + my_array)

[ 0  2  4  6  8 10]


In [9]:
# subtrair dois arrays
print(my_array - my_array)

[0 0 0 0 0 0]


## 2.2 Operador de multiplicação (*) e divisão (/)

In [10]:
# fazer a operação de multiplicação na lista
print(my_list * 2)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]


In [11]:
# fazer a operação de multiplicação no array
print(my_array * 2)

[ 0  2  4  6  8 10]


In [12]:
# fazer a operação de divisão no array
print(my_array / 2)

[0.  0.5 1.  1.5 2.  2.5]


# 3. Criando matrizes

Uma matriz é uma estrutura composta de **n** linhas por **m** colunas.

In [13]:
# criando uma matriz a partir de listas
matrix_1 = np.array([my_list, my_list ,my_list])
matrix_1

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [14]:
# criando uma matriz a partir de arrays
matrix_2 = np.array([my_array, my_array ,my_array])
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

Em uma matriz todas as linhas contém a mesma quantidade de elementos.

In [15]:
# criar uma matriz com uma quantidade diferente de elementos na linha
matrix_3 = np.array([[1, 2], [1, 2], [1, 2, 3]])
matrix_3

/home/carlos/miniconda3/envs/synapse/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


array([list([1, 2]), list([1, 2]), list([1, 2, 3])], dtype=object)

In [16]:
# criando uma matriz com valores zerados
matrix_4 = np.zeros((3,6))
matrix_4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 4. Operações com matrizes

## 4.1 Operador de soma (+) e subtração (-)

In [17]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [18]:
# fazer operação de soma
matrix_2 + 3

array([[3, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 7, 8]])

In [19]:
# fazer operação de subtração
matrix_2 - 3

array([[-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2]])

In [20]:
# visualizar novamente a matriz 3 mal formatada
matrix_3

array([list([1, 2]), list([1, 2]), list([1, 2, 3])], dtype=object)

In [21]:
# usar o operador de soma
print(matrix_3 + 3)

TypeError: can only concatenate list (not "int") to list

## 4.2 Operador de multiplicação (*) e divisão (/)

In [22]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [23]:
# fazer a operação de multiplicação na matriz
print(matrix_2 * 2)

[[ 0  2  4  6  8 10]
 [ 0  2  4  6  8 10]
 [ 0  2  4  6  8 10]]


In [24]:
# fazer a operação de divisão na matriz
print(matrix_2 / matrix_2)

[[nan  1.  1.  1.  1.  1.]
 [nan  1.  1.  1.  1.  1.]
 [nan  1.  1.  1.  1.  1.]]


/home/carlos/miniconda3/envs/synapse/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


# 5. Seleção e atribuição de valores

## 5.1. Listas e vetores

In [25]:
# criar uma lista
print(my_list)

# selecionar o valor da lista na posição 3
print(my_list[3])

# selecionar o valor da lista na última posição
print(my_list[-1])

# mudar o valor da posição 0
my_list[0] = 6
print(my_list)

[0, 1, 2, 3, 4, 5]
3
5
[6, 1, 2, 3, 4, 5]


In [26]:
# criar um array
print(my_array)

# selecionar o valor da lista na posição 3
print(my_array[3])

# selecionar o valor da lista na última posição
print(my_array[-1])

# mudar o valor da posição 0
my_array[0] = 6
print(my_array)

[0 1 2 3 4 5]
3
5
[6 1 2 3 4 5]


## 5.2. Matrizes

In [27]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [28]:
# selecionar o valor da matriz na posição 2,3
print(matrix_2[2,3])

3


In [29]:
# selecionar o último valor da matriz da linha 1
print(matrix_2[1,-1])

5


In [30]:
# mudar o valor da posição 0,0
matrix_2_tmp = matrix_2.copy()

matrix_2_tmp[0,0] = 6
matrix_2_tmp

array([[6, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

# 6. Transformações de matrizes

## 6.1. Operações com linhas e colunas (axis)

In [31]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [32]:
# somar todos elementos de cada coluna
sum_by_cols = np.sum(matrix_2, axis=0)
sum_by_cols

array([ 0,  3,  6,  9, 12, 15])

In [33]:
# somar todos elementos de cada linha
sum_by_rows = np.sum(matrix_2, axis=1)
sum_by_rows

array([15, 15, 15])

## 6.2. Obter a média (mean)

In [34]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [35]:
# pegar a média de toda a matriz
mean = np.mean(matrix_2)
mean

2.5

In [36]:
# pegar a média por coluna
mean_by_cols = np.mean(matrix_2, axis=0)
mean_by_cols

array([0., 1., 2., 3., 4., 5.])

In [37]:
# pegar a média por linha
mean_by_rows = np.mean(matrix_2, axis=1)
mean_by_rows

array([2.5, 2.5, 2.5])

## 6.3. Transposição (T)

In [38]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [39]:
# transpor a matriz 2
matrix_2.T

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [40]:
# transpor um vetor qualquer
my_array.T

array([6, 1, 2, 3, 4, 5])

## 6.4. Produto entre vetores e matrizes (dot)

### 6.4.1. Produto escalar entre vetores

$$\vec a \cdot \vec b = \sum_{i=1}^{n} a_i b_i$$

In [41]:
# mostrar o vetor
print(my_array)

# fazer o produto interno com dois vetores
np.dot(my_array, my_array)

[6 1 2 3 4 5]


91

### 6.4.2. Multiplicação de matrizes

<img src="images/matrix_scalar_product.jpg" width=720 height=512/>

_fonte: https://www.reddit.com/r/learnmath/comments/7mje71/linear_algebra_matrix_multiplication_vs_dot/_

In [42]:
# criar as duas matrizes do exemplo
matrix_ex1 = np.array([[1,2,3],[3,2,1]])
matrix_ex2 = np.array([[1,2],[3,2],[2,7]])

print(matrix_ex1)
print(matrix_ex2)

[[1 2 3]
 [3 2 1]]
[[1 2]
 [3 2]
 [2 7]]


In [43]:
# fazer o produto entre matrizes
np.dot(matrix_ex1, matrix_ex2)

array([[13, 27],
       [11, 17]])

Operação entre matrizes só funciona com dimensões: **(m x n) . (n x m)**

In [44]:
# visualizar novamente a matriz 2
matrix_2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [45]:
# verificar as dimensões da matriz 2
matrix_2.shape

(3, 6)

In [46]:
# fazer o produto da matriz 2 com ela mesmo
np.dot(matrix_2, matrix_2)

ValueError: shapes (3,6) and (3,6) not aligned: 6 (dim 1) != 3 (dim 0)

In [47]:
# fazer o produto da matriz 2 com a transposta
np.dot(matrix_2, matrix_2.T)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])